### ISSUE TITLE
Customizable webhook headers

### ISSUE THREAD

**Issue by fcurella** [robinhood/thorn#11]
Currently, it's possible to customize the payload sent by using `webhook_payload`.

I think it could be useful to add a way to customize headers as well. It would allow, for example, to include an `Authorize` header so that the receiving endpoint could associate the event to a user (eg a 'system' user with admin permission).

This could be implemented as either as `webhook_header` in the model (that'd be my favorite option), or even just some kind of global settings.

If this is something you think it's useful, I can work on a PR.

**Comment by ask** [comment]
That sounds like a good idea!    I would be happy to merge such a patch

**Comment by fcurella** [comment]
Closed in #13
